version: '3.9'

services:
  online-shop:
    build: ./
    command: ./wait-for-postgres.sh db ./online-shop
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=secret

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
    ports:
      - 5433:5432